version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: unp-reservas-app
    container_name: unp_reservas_app
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: unp_reservas_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - unp_db_data:/var/lib/mysql

volumes:
  unp_db_data: